apiVersion: v1
kind: Service
metadata:
  name: fashion-backend-service
  namespace: fashion-platform
spec:
  selector:
    app: fashion-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort