apiVersion: v1
kind: Service
metadata:
  name: fashion-frontend-service
  namespace: fashion-platform
spec:
  selector:
    app: fashion-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer