apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashion-backend
  namespace: fashion-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fashion-backend
  template:
    metadata:
      labels:
        app: fashion-backend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: fashion-backend
          image: 021859068728.dkr.ecr.us-east-1.amazonaws.com/fashion-backend:3b7d9bef6189406f07e4e37d15e2bbffba7a965a
          ports:
            - containerPort: 5000
          env:
            - name: DB_URL
              value: "mongodb://mongo:27017/fashion-store"
            - name: PORT
              value: "5000"
              #env file is used in the dockerfile, so we need to set the environment variables here as well